### ISSUE TITLE
Failed to open BAI index

### ISSUE THREAD

**Issue by mokhouja** [Dr-TSteimle/sv-finder#1]
Hi,
I've been trying to run multiple bam files and keep getting the following error that the sv-finder can't open bai index files.
My bam files are produced with bowtie2, sorted and indexed. I've already tried re-indexing by samtools without any luck.

I ran it with RUST_BACTRACE=1 so you can see at which point it is breaking.

[Bam parser] parsing bam file: test/
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "Failed to open BAI index: No such file or directory (os error 2)" }', src/main.rs:112:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/result.rs:1107:23
   4: sv_finder::main
             at /home/thomas/Documents/GitHub/sv-finder/src/main.rs:112:22
   5: core::ops::function::FnOnce::call_once
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Dr-TSteimle** [comment]
Thank you for reporting the issue.
What is the command you've run ?

Best

**Comment by mokhouja** [comment]
Hi Thomas,
here is the command I've used: ./sv-finder -b bamfilename -f Homo_sapiens.GRCh38.dna.primary_assembly.fa -c cytoBandIdeo.txt
It worked now after I've removed the binary files and re-downloaded it. Appearently it was something wrong on our side.

Thank you for your input!
